[package]
name = "guard"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macros = { path = "macros", optional = true }

[features]
default = ["macros"]
macros = ["dep:macros"]
